GET /api/articles/:article_id/comments endpoint
ro25ck/my_news_project pull request #5
Opened 2023-10-05 15:31 UTC by ro25ck

this pull request generates the following:

- creates a GET /api/articles/:article_id/comments endpoint
- modified associated articles controller and model JS files with appropriate functions and callbacks
- utilises TDD tests for:
        - returns 200 status & an array of comment objects with requested properties for specified article id
        - error test 404 if provided an article_id that doesn't exist in database.
        - error test 400 if provided an article_id that is invalid id.

2023-10-05 15:48 UTC, itsaliabdallah requested changes
I'd like to see a 200 test.
If an article has no comments ideally you want to send an empty array back.

Before you send your request off to get the comments you'd want to know that the article exists first.
You have a model already that checks for an article by ID

2023-10-05 15:48 UTC, itsaliabdallah commented on controllers/articles.controller.js
> +    })
PSQL would throw an error here

2023-10-05 15:48 UTC, itsaliabdallah commented on models/articles.model.js
> +                }
If an empty array comes back its not an error it just means that there is no comments with that article which you would want to send back to the client.

2023-10-06 09:08 UTC, yalicee approved these changes
could you explain to what the promise.all is doing on line 32? Because you seem to have already done it on line 29. However I can see that this works so approved anyway

2023-10-06 09:08 UTC, yalicee commented on controllers/articles.controller.js
> +            return Promise.all([fetchArticleById(article_id), fetchCommentsByArticleId(article_id)])
What is this line doing?

2023-10-06 12:51 UTC, ro25ck commented on controllers/articles.controller.js
> +            return Promise.all([fetchArticleById(article_id), fetchCommentsByArticleId(article_id)])
Summing our direct messages here.

It is to verify if the article_id exists in the database and if so, go on to fetch the comments.  As the promiseAll returns 2 results in the array, a the successful fetch of comments is in the 1 index of the array.  Also, error if the first promise (fails to find article with the id), the error is then passed along and handled appropriately.

You suggested using a promise chain to achieve the same result.

2023-10-06 13:07 UTC, merged